//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod zosta³ wygenerowany przez narzêdzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mog¹ spowodowaæ nieprawid³owe zachowanie i zostan¹ utracone, jeœli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodbookApp.Localization {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagaj¹ca zdefiniowania typu do wyszukiwania zlokalizowanych ci¹gów itd.
    /// </summary>
    // Ta klasa zosta³a automatycznie wygenerowana za pomoc¹ klasy StronglyTypedResourceBuilder
    // przez narzêdzie, takie jak ResGen lub Visual Studio.
    // Aby dodaæ lub usun¹æ sk³adow¹, edytuj plik ResX, a nastêpnie ponownie uruchom narzêdzie ResGen
    // z opcj¹ /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CategoryFormPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CategoryFormPageResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wyst¹pienie ResourceManager u¿ywane przez tê klasê.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.CategoryFormPageResources", typeof(CategoryFormPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przes³ania w³aœciwoœæ CurrentUICulture bie¿¹cego w¹tku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomoc¹ tej klasy zasobów wymagaj¹cej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu New Folder.
        /// </summary>
        internal static string NewFolderTitle {
            get {
                return ResourceManager.GetString("NewFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Edit Folder.
        /// </summary>
        internal static string EditFolderTitle {
            get {
                return ResourceManager.GetString("EditFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Folder Name.
        /// </summary>
        internal static string FolderName {
            get {
                return ResourceManager.GetString("FolderName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Enter folder name.
        /// </summary>
        internal static string FolderNamePlaceholder {
            get {
                return ResourceManager.GetString("FolderNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Description (optional).
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Enter folder description.
        /// </summary>
        internal static string DescriptionPlaceholder {
            get {
                return ResourceManager.GetString("DescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu Edit Folder.
        /// </summary>
        internal static string EditFolder {
            get {
                return ResourceManager.GetString("EditFolder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ci¹g podobny do ci¹gu New Folder.
        /// </summary>
        internal static string NewFolder {
            get {
                return ResourceManager.GetString("NewFolder", resourceCulture);
            }
        }
    }
}