// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace FoodbookApp.Localization {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CRUDComponentPopupResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal CRUDComponentPopupResources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.CRUDComponentPopupResources", typeof(CRUDComponentPopupResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        internal static string NamePlaceholder {
            get {
                return ResourceManager.GetString("NamePlaceholder", resourceCulture);
            }
        }
        
        internal static string ColorLabel {
            get {
                return ResourceManager.GetString("ColorLabel", resourceCulture);
            }
        }
        
        internal static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        internal static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        internal static string SaveButton_Add {
            get {
                return ResourceManager.GetString("SaveButton_Add", resourceCulture);
            }
        }
        
        internal static string SaveButton_Save {
            get {
                return ResourceManager.GetString("SaveButton_Save", resourceCulture);
            }
        }
        
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        internal static string CloseButton {
            get {
                return ResourceManager.GetString("CloseButton", resourceCulture);
            }
        }
        
        internal static string ListHeader {
            get {
                return ResourceManager.GetString("ListHeader", resourceCulture);
            }
        }
        
        // New: color names
        internal static string Color_Red {
            get {
                return ResourceManager.GetString("Color_Red", resourceCulture);
            }
        }
        
        internal static string Color_Pink {
            get {
                return ResourceManager.GetString("Color_Pink", resourceCulture);
            }
        }
        
        internal static string Color_Purple {
            get {
                return ResourceManager.GetString("Color_Purple", resourceCulture);
            }
        }
        
        internal static string Color_Indigo {
            get {
                return ResourceManager.GetString("Color_Indigo", resourceCulture);
            }
        }
        
        internal static string Color_Blue {
            get {
                return ResourceManager.GetString("Color_Blue", resourceCulture);
            }
        }
        
        internal static string Color_LightBlue {
            get {
                return ResourceManager.GetString("Color_LightBlue", resourceCulture);
            }
        }
        
        internal static string Color_Cyan {
            get {
                return ResourceManager.GetString("Color_Cyan", resourceCulture);
            }
        }
        
        internal static string Color_Teal {
            get {
                return ResourceManager.GetString("Color_Teal", resourceCulture);
            }
        }
        
        internal static string Color_Green {
            get {
                return ResourceManager.GetString("Color_Green", resourceCulture);
            }
        }
        
        internal static string Color_LightGreen {
            get {
                return ResourceManager.GetString("Color_LightGreen", resourceCulture);
            }
        }
        
        internal static string Color_Lime {
            get {
                return ResourceManager.GetString("Color_Lime", resourceCulture);
            }
        }
        
        internal static string Color_Yellow {
            get {
                return ResourceManager.GetString("Color_Yellow", resourceCulture);
            }
        }
        
        internal static string Color_Orange {
            get {
                return ResourceManager.GetString("Color_Orange", resourceCulture);
            }
        }
        
        internal static string Color_DeepOrange {
            get {
                return ResourceManager.GetString("Color_DeepOrange", resourceCulture);
            }
        }
        
        internal static string Color_Brown {
            get {
                return ResourceManager.GetString("Color_Brown", resourceCulture);
            }
        }
        
        internal static string Color_Gray {
            get {
                return ResourceManager.GetString("Color_Gray", resourceCulture);
            }
        }
    }
}
