//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodbookApp.Localization {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataArchivizationPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataArchivizationPageResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.DataArchivizationPageResources", typeof(DataArchivizationPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CreateArchiveButton => ResourceManager.GetString("CreateArchiveButton", resourceCulture);
        internal static string HeaderDescription => ResourceManager.GetString("HeaderDescription", resourceCulture);
        internal static string HeaderTitle => ResourceManager.GetString("HeaderTitle", resourceCulture);
        internal static string RestoreArchiveButton => ResourceManager.GetString("RestoreArchiveButton", resourceCulture);
        internal static string RestoreDescription => ResourceManager.GetString("RestoreDescription", resourceCulture);
        internal static string RestoreHeader => ResourceManager.GetString("RestoreHeader", resourceCulture);
        internal static string Title => ResourceManager.GetString("Title", resourceCulture);

        // New exposed keys used in code-behind
        internal static string DefaultFolderLabel => ResourceManager.GetString("DefaultFolderLabel", resourceCulture);
        internal static string RefreshList => ResourceManager.GetString("RefreshList", resourceCulture);
        internal static string ArchivesInFolder => ResourceManager.GetString("ArchivesInFolder", resourceCulture);
        internal static string NoArchivesFound => ResourceManager.GetString("NoArchivesFound", resourceCulture);
        internal static string RestoreFromThis => ResourceManager.GetString("RestoreFromThis", resourceCulture);
        internal static string ArchiveNameLabel => ResourceManager.GetString("ArchiveNameLabel", resourceCulture);
        internal static string ArchiveNamePlaceholder => ResourceManager.GetString("ArchiveNamePlaceholder", resourceCulture);
        internal static string DeleteFromThis => ResourceManager.GetString("DeleteFromThis", resourceCulture);
        internal static string NoArchivesInDefault => ResourceManager.GetString("NoArchivesInDefault", resourceCulture);
        internal static string ConfirmTitle => ResourceManager.GetString("ConfirmTitle", resourceCulture);
        internal static string ConfirmDelete => ResourceManager.GetString("ConfirmDelete", resourceCulture);
        internal static string DeletedMessage => ResourceManager.GetString("DeletedMessage", resourceCulture);
        internal static string ArchiveCreatedSuffix => ResourceManager.GetString("ArchiveCreatedSuffix", resourceCulture);
        internal static string RestoreSuccess => ResourceManager.GetString("RestoreSuccess", resourceCulture);
        internal static string SearchArchivesButton => ResourceManager.GetString("SearchArchivesButton", resourceCulture);
        internal static string ErrorLoadingList => ResourceManager.GetString("ErrorLoadingList", resourceCulture);
        internal static string PickArchiveTitle => ResourceManager.GetString("PickArchiveTitle", resourceCulture);
        internal static string ManualSearchDone => ResourceManager.GetString("ManualSearchDone", resourceCulture);
        internal static string ErrorTitle => ResourceManager.GetString("ErrorTitle", resourceCulture);
        internal static string InfoTitle => ResourceManager.GetString("InfoTitle", resourceCulture);
        internal static string ManualSearchFailed => ResourceManager.GetString("ManualSearchFailed", resourceCulture);
        internal static string SavedMessage => ResourceManager.GetString("SavedMessage", resourceCulture);
        internal static string ExportFailed => ResourceManager.GetString("ExportFailed", resourceCulture);
        internal static string ImportFailed => ResourceManager.GetString("ImportFailed", resourceCulture);
        internal static string DeleteFailed => ResourceManager.GetString("DeleteFailed", resourceCulture);
        internal static string RestoreFailed => ResourceManager.GetString("RestoreFailed", resourceCulture);
    }
}
