// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>

namespace FoodbookApp.Localization {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FilterSortPopupResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal FilterSortPopupResources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.FilterSortPopupResources", typeof(FilterSortPopupResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        internal static string SortLabel {
            get {
                return ResourceManager.GetString("SortLabel", resourceCulture);
            }
        }
        
        internal static string LabelsHeader {
            get {
                return ResourceManager.GetString("LabelsHeader", resourceCulture);
            }
        }
        
        internal static string IngredientsHeader {
            get {
                return ResourceManager.GetString("IngredientsHeader", resourceCulture);
            }
        }
        
        internal static string ApplyButton {
            get {
                return ResourceManager.GetString("ApplyButton", resourceCulture);
            }
        }
        
        internal static string ClearButton {
            get {
                return ResourceManager.GetString("ClearButton", resourceCulture);
            }
        }
        
        internal static string IngredientSearchPlaceholder {
            get {
                return ResourceManager.GetString("IngredientSearchPlaceholder", resourceCulture);
            }
        }
        
        internal static string SortAZ {
            get {
                return ResourceManager.GetString("SortAZ", resourceCulture);
            }
        }
        
        internal static string SortZA {
            get {
                return ResourceManager.GetString("SortZA", resourceCulture);
            }
        }
        
        internal static string SortCaloriesAsc {
            get {
                return ResourceManager.GetString("SortCaloriesAsc", resourceCulture);
            }
        }
        
        internal static string SortCaloriesDesc {
            get {
                return ResourceManager.GetString("SortCaloriesDesc", resourceCulture);
            }
        }
        
        internal static string SortProteinAsc {
            get {
                return ResourceManager.GetString("SortProteinAsc", resourceCulture);
            }
        }
        
        internal static string SortProteinDesc {
            get {
                return ResourceManager.GetString("SortProteinDesc", resourceCulture);
            }
        }
        
        internal static string SortCarbsAsc {
            get {
                return ResourceManager.GetString("SortCarbsAsc", resourceCulture);
            }
        }
        
        internal static string SortCarbsDesc {
            get {
                return ResourceManager.GetString("SortCarbsDesc", resourceCulture);
            }
        }
        
        internal static string SortFatAsc {
            get {
                return ResourceManager.GetString("SortFatAsc", resourceCulture);
            }
        }
        
        internal static string SortFatDesc {
            get {
                return ResourceManager.GetString("SortFatDesc", resourceCulture);
            }
        }
    }
}
