// <auto-generated>
// This file was auto-generated for FolderResources.
// </auto-generated>
namespace FoodbookApp.Localization {
    using System;
    using System.Reflection;
    using System.Resources;
    using System.Globalization;
    internal class FolderResources {
        private static ResourceManager resourceMan;
        private static CultureInfo resourceCulture;
        internal FolderResources() {}
        internal static ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    resourceMan = new ResourceManager("FoodbookApp.Localization.FolderResources", typeof(FolderResources).Assembly);
                }
                return resourceMan;
            }
        }
        internal static CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }
        internal static string RenameFolderTitle => ResourceManager.GetString("RenameFolderTitle", resourceCulture);
        internal static string RenameFolderPrompt => ResourceManager.GetString("RenameFolderPrompt", resourceCulture);
        internal static string EditDescriptionTitle => ResourceManager.GetString("EditDescriptionTitle", resourceCulture);
        internal static string EditDescriptionPrompt => ResourceManager.GetString("EditDescriptionPrompt", resourceCulture);
        internal static string ValidationNameRequired => ResourceManager.GetString("ValidationNameRequired", resourceCulture);
        internal static string Root {
            get {
                return ResourceManager.GetString("Root", resourceCulture);
            }
        }
        
        internal static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        internal static string ChooseRecipeTitle {
            get {
                return ResourceManager.GetString("ChooseRecipeTitle", resourceCulture);
            }
        }
        
        internal static string EmptyFolderTitle {
            get {
                return ResourceManager.GetString("EmptyFolderTitle", resourceCulture);
            }
        }
        
        internal static string EmptyFolderHint {
            get {
                return ResourceManager.GetString("EmptyFolderHint", resourceCulture);
            }
        }
        
        internal static string FooterHint {
            get {
                return ResourceManager.GetString("FooterHint", resourceCulture);
            }
        }
    }
}
