//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodbookApp.Localization {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PlannerListsPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlannerListsPageResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.PlannerListsPageResources", typeof(PlannerListsPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }
        
        internal static string EmptyHint {
            get {
                return ResourceManager.GetString("EmptyHint", resourceCulture);
            }
        }
        
        internal static string PlannerTitle {
            get {
                return ResourceManager.GetString("PlannerTitle", resourceCulture);
            }
        }
        
        internal static string PlansTabTitle {
            get {
                return ResourceManager.GetString("PlansTabTitle", resourceCulture);
            }
        }
        
        internal static string FoodbooksTabTitle {
            get {
                return ResourceManager.GetString("FoodbooksTabTitle", resourceCulture);
            }
        }
        
        internal static string FoodbooksEmptyTitle {
            get {
                return ResourceManager.GetString("FoodbooksEmptyTitle", resourceCulture);
            }
        }
        
        internal static string FoodbooksEmptyHint {
            get {
                return ResourceManager.GetString("FoodbooksEmptyHint", resourceCulture);
            }
        }
        
        internal static string ArchiveFoodbookTitle {
            get {
                return ResourceManager.GetString("ArchiveFoodbookTitle", resourceCulture);
            }
        }
        
        internal static string ArchiveFoodbookMessage {
            get {
                return ResourceManager.GetString("ArchiveFoodbookMessage", resourceCulture);
            }
        }
        
        internal static string ApplyFoodbookTitle {
            get {
                return ResourceManager.GetString("ApplyFoodbookTitle", resourceCulture);
            }
        }
        
        internal static string ApplyFoodbookPrompt {
            get {
                return ResourceManager.GetString("ApplyFoodbookPrompt", resourceCulture);
            }
        }
        
        internal static string ApplyFoodbookAccept {
            get {
                return ResourceManager.GetString("ApplyFoodbookAccept", resourceCulture);
            }
        }
        
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        internal static string InvalidDateMessage {
            get {
                return ResourceManager.GetString("InvalidDateMessage", resourceCulture);
            }
        }
        
        internal static string OverlapTitle {
            get {
                return ResourceManager.GetString("OverlapTitle", resourceCulture);
            }
        }
        
        internal static string OverlapMessage {
            get {
                return ResourceManager.GetString("OverlapMessage", resourceCulture);
            }
        }
        
        internal static string ApplySuccessTitle {
            get {
                return ResourceManager.GetString("ApplySuccessTitle", resourceCulture);
            }
        }
        
        internal static string ApplySuccessMessage {
            get {
                return ResourceManager.GetString("ApplySuccessMessage", resourceCulture);
            }
        }
        
        internal static string ArchivePlanTitle {
            get {
                return ResourceManager.GetString("ArchivePlanTitle", resourceCulture);
            }
        }
        
        internal static string ArchivePlanMessage {
            get {
                return ResourceManager.GetString("ArchivePlanMessage", resourceCulture);
            }
        }
    }
}
