//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodbookApp.Localization {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProfilePageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProfilePageResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.ProfilePageResources", typeof(ProfilePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cloud Synchronization.
        /// </summary>
        internal static string CloudSyncHeader {
            get {
                return ResourceManager.GetString("CloudSyncHeader", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Disabling sync....
        /// </summary>
        internal static string DisablingSync {
            get {
                return ResourceManager.GetString("DisablingSync", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu name@example.com.
        /// </summary>
        internal static string EmailPlaceholder {
            get {
                return ResourceManager.GetString("EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Email cannot be empty..
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enable cloud data sync.
        /// </summary>
        internal static string EnableCloudSync {
            get {
                return ResourceManager.GetString("EnableCloudSync", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enabling sync....
        /// </summary>
        internal static string EnablingSync {
            get {
                return ResourceManager.GetString("EnablingSync", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Force sync now.
        /// </summary>
        internal static string ForceSyncButton {
            get {
                return ResourceManager.GetString("ForceSyncButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Force sync completed.
        /// </summary>
        internal static string ForceSyncCompletedTitle {
            get {
                return ResourceManager.GetString("ForceSyncCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cloud duplicates removed: {0}.
        /// </summary>
        internal static string ForceSyncDuplicatesRemoved {
            get {
                return ResourceManager.GetString("ForceSyncDuplicatesRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Duration: {0}s.
        /// </summary>
        internal static string ForceSyncDuration {
            get {
                return ResourceManager.GetString("ForceSyncDuration", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error: {0}.
        /// </summary>
        internal static string ForceSyncError {
            get {
                return ResourceManager.GetString("ForceSyncError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Force sync error.
        /// </summary>
        internal static string ForceSyncErrorTitle {
            get {
                return ResourceManager.GetString("ForceSyncErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Failed: {0}.
        /// </summary>
        internal static string ForceSyncFailed {
            get {
                return ResourceManager.GetString("ForceSyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Remaining: {0}.
        /// </summary>
        internal static string ForceSyncRemaining {
            get {
                return ResourceManager.GetString("ForceSyncRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Skipped (already in cloud): {0}.
        /// </summary>
        internal static string ForceSyncSkipped {
            get {
                return ResourceManager.GetString("ForceSyncSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Synced: {0}.
        /// </summary>
        internal static string ForceSyncSynced {
            get {
                return ResourceManager.GetString("ForceSyncSynced", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Forcing sync of ALL items....
        /// </summary>
        internal static string ForcingSync {
            get {
                return ResourceManager.GetString("ForcingSync", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        /// </summary>
        internal static string GenericErrorTitle {
            get {
                return ResourceManager.GetString("GenericErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign in to Supabase.
        /// </summary>
        internal static string HeaderSubtitle {
            get {
                return ResourceManager.GetString("HeaderSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Profile.
        /// </summary>
        internal static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu You are signed in.
        /// </summary>
        internal static string LoggedInTitle {
            get {
                return ResourceManager.GetString("LoggedInTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Signing in....
        /// </summary>
        internal static string LoggingIn {
            get {
                return ResourceManager.GetString("LoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign in.
        /// </summary>
        internal static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login failed. Please check your credentials..
        /// </summary>
        internal static string LoginErrorMessage {
            get {
                return ResourceManager.GetString("LoginErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Login Error.
        /// </summary>
        internal static string LoginErrorTitle {
            get {
                return ResourceManager.GetString("LoginErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign in.
        /// </summary>
        internal static string LoginPanelTitle {
            get {
                return ResourceManager.GetString("LoginPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign out.
        /// </summary>
        internal static string LogoutButton {
            get {
                return ResourceManager.GetString("LogoutButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Logout Error.
        /// </summary>
        internal static string LogoutErrorTitle {
            get {
                return ResourceManager.GetString("LogoutErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password.
        /// </summary>
        internal static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Enter password.
        /// </summary>
        internal static string PasswordPlaceholder {
            get {
                return ResourceManager.GetString("PasswordPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Password cannot be empty..
        /// </summary>
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Register.
        /// </summary>
        internal static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Authentication service not found..
        /// </summary>
        internal static string ServiceMissingMessage {
            get {
                return ResourceManager.GetString("ServiceMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Service unavailable.
        /// </summary>
        internal static string ServiceMissingTitle {
            get {
                return ResourceManager.GetString("ServiceMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cloud sync disabled.
        /// </summary>
        internal static string SyncDisabled {
            get {
                return ResourceManager.GetString("SyncDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Cloud sync enabled. Syncing data....
        /// </summary>
        internal static string SyncEnabled {
            get {
                return ResourceManager.GetString("SyncEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sync Error.
        /// </summary>
        internal static string SyncErrorTitle {
            get {
                return ResourceManager.GetString("SyncErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Removing duplicates....
        /// </summary>
        internal static string SyncOverlayDeduplicating {
            get {
                return ResourceManager.GetString("SyncOverlayDeduplicating", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Fetching cloud data....
        /// </summary>
        internal static string SyncOverlayFetching {
            get {
                return ResourceManager.GetString("SyncOverlayFetching", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Syncing data....
        /// </summary>
        internal static string SyncOverlaySyncing {
            get {
                return ResourceManager.GetString("SyncOverlaySyncing", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sync service not available.
        /// </summary>
        internal static string SyncServiceUnavailable {
            get {
                return ResourceManager.GetString("SyncServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Status: {0}, Pending: {1}.
        /// </summary>
        internal static string SyncStatusFormat {
            get {
                return ResourceManager.GetString("SyncStatusFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Profile.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Account service is unavailable..
        /// </summary>
        internal static string SyncQueueAccountUnavailable {
            get {
                return ResourceManager.GetString("SyncQueueAccountUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ID: {0}.
        /// </summary>
        internal static string SyncQueueDetailCompletedFormat {
            get {
                return ResourceManager.GetString("SyncQueueDetailCompletedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error: {0}.
        /// </summary>
        internal static string SyncQueueDetailErrorFormat {
            get {
                return ResourceManager.GetString("SyncQueueDetailErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operation failed.
        /// </summary>
        internal static string SyncQueueDetailErrorNoMessage {
            get {
                return ResourceManager.GetString("SyncQueueDetailErrorNoMessage", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operation in progress.
        /// </summary>
        internal static string SyncQueueDetailInProgress {
            get {
                return ResourceManager.GetString("SyncQueueDetailInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Operation pending in queue.
        /// </summary>
        internal static string SyncQueueDetailPending {
            get {
                return ResourceManager.GetString("SyncQueueDetailPending", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No entries in sync queue..
        /// </summary>
        internal static string SyncQueueEmpty {
            get {
                return ResourceManager.GetString("SyncQueueEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sign in to view sync queue..
        /// </summary>
        internal static string SyncQueueLoginRequired {
            get {
                return ResourceManager.GetString("SyncQueueLoginRequired", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Loading....
        /// </summary>
        internal static string SyncQueueLoading {
            get {
                return ResourceManager.GetString("SyncQueueLoading", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Could not load sync queue..
        /// </summary>
        internal static string SyncQueueLoadError {
            get {
                return ResourceManager.GetString("SyncQueueLoadError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu No active account..
        /// </summary>
        internal static string SyncQueueNoActiveAccount {
            get {
                return ResourceManager.GetString("SyncQueueNoActiveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Recent operations.
        /// </summary>
        internal static string SyncQueueRecentOperations {
            get {
                return ResourceManager.GetString("SyncQueueRecentOperations", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Refresh.
        /// </summary>
        internal static string SyncQueueRefresh {
            get {
                return ResourceManager.GetString("SyncQueueRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Application services are unavailable..
        /// </summary>
        internal static string SyncQueueServiceUnavailable {
            get {
                return ResourceManager.GetString("SyncQueueServiceUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Error.
        /// </summary>
        internal static string SyncQueueStatusError {
            get {
                return ResourceManager.GetString("SyncQueueStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu In progress.
        /// </summary>
        internal static string SyncQueueStatusInProgress {
            get {
                return ResourceManager.GetString("SyncQueueStatusInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Pending.
        /// </summary>
        internal static string SyncQueueStatusPending {
            get {
                return ResourceManager.GetString("SyncQueueStatusPending", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Success.
        /// </summary>
        internal static string SyncQueueStatusSuccess {
            get {
                return ResourceManager.GetString("SyncQueueStatusSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Status operacji SyncQueue.
        /// </summary>
        internal static string SyncQueueSubtitle {
            get {
                return ResourceManager.GetString("SyncQueueSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Total: {0} · ⬆️ {1} · ⬇️ {2} · Success: {3} · Errors: {4} · Pending: {5}.
        /// </summary>
        internal static string SyncQueueSummaryFormat {
            get {
                return ResourceManager.GetString("SyncQueueSummaryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sync queue.
        /// </summary>
        internal static string SyncQueueTitle {
            get {
                return ResourceManager.GetString("SyncQueueTitle", resourceCulture);
            }
        }
    }
}
