//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodbookApp.Localization {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsPageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPageResources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.SettingsPageResources", typeof(SettingsPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu FoodBook App.
        /// </summary>
        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Author: Przemyslaw Przybyszewski.
        /// </summary>
        internal static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Background.
        /// </summary>
        internal static string ColorfulBackgroundOption {
            get {
                return ResourceManager.GetString("ColorfulBackgroundOption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Autumn.
        /// </summary>
        internal static string ColorThemeAutumn {
            get {
                return ResourceManager.GetString("ColorThemeAutumn", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Default.
        /// </summary>
        internal static string ColorThemeDefault {
            get {
                return ResourceManager.GetString("ColorThemeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu App color palette.
        /// </summary>
        internal static string ColorThemeDescription {
            get {
                return ResourceManager.GetString("ColorThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Mint.
        /// </summary>
        internal static string ColorThemeMint {
            get {
                return ResourceManager.GetString("ColorThemeMint", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monochrome.
        /// </summary>
        internal static string ColorThemeMonochrome {
            get {
                return ResourceManager.GetString("ColorThemeMonochrome", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Nature.
        /// </summary>
        internal static string ColorThemeNature {
            get {
                return ResourceManager.GetString("ColorThemeNature", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Navy.
        /// </summary>
        internal static string ColorThemeNavy {
            get {
                return ResourceManager.GetString("ColorThemeNavy", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Color Theme.
        /// </summary>
        internal static string ColorThemeTitle {
            get {
                return ResourceManager.GetString("ColorThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Vibrant.
        /// </summary>
        internal static string ColorThemeVibrant {
            get {
                return ResourceManager.GetString("ColorThemeVibrant", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Warm.
        /// </summary>
        internal static string ColorThemeWarm {
            get {
                return ResourceManager.GetString("ColorThemeWarm", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Soon.
        /// </summary>
        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Execute Migration.
        /// </summary>
        internal static string DatabaseMigrationButton {
            get {
                return ResourceManager.GetString("DatabaseMigrationButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Update database structure to the latest version.
        /// </summary>
        internal static string DatabaseMigrationDescription {
            get {
                return ResourceManager.GetString("DatabaseMigrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Database Migration.
        /// </summary>
        internal static string DatabaseMigrationTitle {
            get {
                return ResourceManager.GetString("DatabaseMigrationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Reset Database.
        /// </summary>
        internal static string DatabaseResetButton {
            get {
                return ResourceManager.GetString("DatabaseResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu ⚠️ Delete all data and restore default settings.
        /// </summary>
        internal static string DatabaseResetDescription {
            get {
                return ResourceManager.GetString("DatabaseResetDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Database Reset.
        /// </summary>
        internal static string DatabaseResetTitle {
            get {
                return ResourceManager.GetString("DatabaseResetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Irreversible operation!.
        /// </summary>
        internal static string DatabaseResetWarning {
            get {
                return ResourceManager.GetString("DatabaseResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Save recipes and plans.
        /// </summary>
        internal static string DataExportDescription {
            get {
                return ResourceManager.GetString("DataExportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Data export.
        /// </summary>
        internal static string DataExportTitle {
            get {
                return ResourceManager.GetString("DataExportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu System Default.
        /// </summary>
        internal static string FontFamilyDefault {
            get {
                return ResourceManager.GetString("FontFamilyDefault", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Text typeface.
        /// </summary>
        internal static string FontFamilyDescription {
            get {
                return ResourceManager.GetString("FontFamilyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Monospace.
        /// </summary>
        internal static string FontFamilyMonospace {
            get {
                return ResourceManager.GetString("FontFamilyMonospace", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Sans-serif.
        /// </summary>
        internal static string FontFamilySansSerif {
            get {
                return ResourceManager.GetString("FontFamilySansSerif", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Serif.
        /// </summary>
        internal static string FontFamilySerif {
            get {
                return ResourceManager.GetString("FontFamilySerif", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Font Family.
        /// </summary>
        internal static string FontFamilyTitle {
            get {
                return ResourceManager.GetString("FontFamilyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Default.
        /// </summary>
        internal static string FontSizeDefault {
            get {
                return ResourceManager.GetString("FontSizeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Text size.
        /// </summary>
        internal static string FontSizeDescription {
            get {
                return ResourceManager.GetString("FontSizeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Extra Large.
        /// </summary>
        internal static string FontSizeExtraLarge {
            get {
                return ResourceManager.GetString("FontSizeExtraLarge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Large.
        /// </summary>
        internal static string FontSizeLarge {
            get {
                return ResourceManager.GetString("FontSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Small.
        /// </summary>
        internal static string FontSizeSmall {
            get {
                return ResourceManager.GetString("FontSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Font Size.
        /// </summary>
        internal static string FontSizeTitle {
            get {
                return ResourceManager.GetString("FontSizeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Personalize your application.
        /// </summary>
        internal static string HeaderSubtitle {
            get {
                return ResourceManager.GetString("HeaderSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Interface language.
        /// </summary>
        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu English.
        /// </summary>
        internal static string LanguageEnglish {
            get {
                return ResourceManager.GetString("LanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Polish.
        /// </summary>
        internal static string LanguagePolish {
            get {
                return ResourceManager.GetString("LanguagePolish", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Language.
        /// </summary>
        internal static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu All rights reserved 2025.
        /// </summary>
        internal static string RightsLabel {
            get {
                return ResourceManager.GetString("RightsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Dark.
        /// </summary>
        internal static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light / dark.
        /// </summary>
        internal static string ThemeDescription {
            get {
                return ResourceManager.GetString("ThemeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Light.
        /// </summary>
        internal static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu System.
        /// </summary>
        internal static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Theme.
        /// </summary>
        internal static string ThemeTitle {
            get {
                return ResourceManager.GetString("ThemeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Settings.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Version info.
        /// </summary>
        internal static string VersionInfoTitle {
            get {
                return ResourceManager.GetString("VersionInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Version 1.0.
        /// </summary>
        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }
    }
}
