//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodbookApp.Localization {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomePageResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomePageResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.HomePageResources", typeof(HomePageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }

        internal static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }

        internal static string Recipes {
            get {
                return ResourceManager.GetString("Recipes", resourceCulture);
            }
        }

        internal static string SavedRecipes {
            get {
                return ResourceManager.GetString("SavedRecipes", resourceCulture);
            }
        }

        internal static string Plans {
            get {
                return ResourceManager.GetString("Plans", resourceCulture);
            }
        }

        internal static string ActiveLists {
            get {
                return ResourceManager.GetString("ActiveLists", resourceCulture);
            }
        }

        internal static string PlannedMealsHeader {
            get {
                return ResourceManager.GetString("PlannedMealsHeader", resourceCulture);
            }
        }

        internal static string ClickRecipeHint {
            get {
                return ResourceManager.GetString("ClickRecipeHint", resourceCulture);
            }
        }

        internal static string NutritionStatsHeader {
            get {
                return ResourceManager.GetString("NutritionStatsHeader", resourceCulture);
            }
        }

        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }

        internal static string Protein {
            get {
                return ResourceManager.GetString("Protein", resourceCulture);
            }
        }

        internal static string Carbs {
            get {
                return ResourceManager.GetString("Carbs", resourceCulture);
            }
        }

        internal static string Fats {
            get {
                return ResourceManager.GetString("Fats", resourceCulture);
            }
        }

        internal static string NoNutritionData {
            get {
                return ResourceManager.GetString("NoNutritionData", resourceCulture);
            }
        }

        internal static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }

        internal static string InArchive {
            get {
                return ResourceManager.GetString("InArchive", resourceCulture);
            }
        }

        internal static string GoToArchive {
            get {
                return ResourceManager.GetString("GoToArchive", resourceCulture);
            }
        }

        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }

        internal static string Customize {
            get {
                return ResourceManager.GetString("Customize", resourceCulture);
            }
        }

        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }

        internal static string GoToSettings {
            get {
                return ResourceManager.GetString("GoToSettings", resourceCulture);
            }
        }
    }
}
