//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodbookApp.Localization {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class IngredientsPageResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal IngredientsPageResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.IngredientsPageResources", typeof(IngredientsPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        internal static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }

        internal static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }

        internal static string EmptyTitle {
            get {
                return ResourceManager.GetString("EmptyTitle", resourceCulture);
            }
        }

        internal static string EmptyHint {
            get {
                return ResourceManager.GetString("EmptyHint", resourceCulture);
            }
        }

        internal static string EmptyDialogTitle {
            get {
                return ResourceManager.GetString("EmptyDialogTitle", resourceCulture);
            }
        }

        internal static string EmptyDialogMessage {
            get {
                return ResourceManager.GetString("EmptyDialogMessage", resourceCulture);
            }
        }

        internal static string EmptyDialogConfirm {
            get {
                return ResourceManager.GetString("EmptyDialogConfirm", resourceCulture);
            }
        }

        internal static string EmptyDialogCancel {
            get {
                return ResourceManager.GetString("EmptyDialogCancel", resourceCulture);
            }
        }

        internal static string LoadErrorTitle {
            get {
                return ResourceManager.GetString("LoadErrorTitle", resourceCulture);
            }
        }

        internal static string LoadErrorMessage {
            get {
                return ResourceManager.GetString("LoadErrorMessage", resourceCulture);
            }
        }

        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
    }
}
