//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodbookApp.Localization {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsPageResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsPageResources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoodbookApp.Localization.SettingsPageResources", typeof(SettingsPageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        internal static string HeaderTitle {
            get {
                return ResourceManager.GetString("HeaderTitle", resourceCulture);
            }
        }

        internal static string HeaderSubtitle {
            get {
                return ResourceManager.GetString("HeaderSubtitle", resourceCulture);
            }
        }

        internal static string ThemeTitle {
            get {
                return ResourceManager.GetString("ThemeTitle", resourceCulture);
            }
        }

        internal static string ThemeDescription {
            get {
                return ResourceManager.GetString("ThemeDescription", resourceCulture);
            }
        }

        internal static string LanguageTitle {
            get {
                return ResourceManager.GetString("LanguageTitle", resourceCulture);
            }
        }

        internal static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }

        internal static string VersionInfoTitle {
            get {
                return ResourceManager.GetString("VersionInfoTitle", resourceCulture);
            }
        }

        internal static string VersionNumber {
            get {
                return ResourceManager.GetString("VersionNumber", resourceCulture);
            }
        }

        internal static string AuthorLabel {
            get {
                return ResourceManager.GetString("AuthorLabel", resourceCulture);
            }
        }

        internal static string RightsLabel {
            get {
                return ResourceManager.GetString("RightsLabel", resourceCulture);
            }
        }

        internal static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }

        internal static string DataExportTitle {
            get {
                return ResourceManager.GetString("DataExportTitle", resourceCulture);
            }
        }

        internal static string DataExportDescription {
            get {
                return ResourceManager.GetString("DataExportDescription", resourceCulture);
            }
        }

        internal static string ComingSoon {
            get {
                return ResourceManager.GetString("ComingSoon", resourceCulture);
            }
        }
    }
}
